export const REGISTER_USER = 'REGISTER_USER';
export const USER_LOGIN = 'REGISTER_USER';
export const USER_LOGOUT = 'REGISTER_USER';
export const REMOVE_USER = 'REGISTER_USER';

export const USER_ACTIONS = new Set([ REGISTER_USER,
  USER_LOGIN,
  USER_LOGOUT,
  REMOVE_USER ]);
